#ifndef include_h
#define include_h

#include <LPC23xx.H>                     /* LPC23xx definitions               */

#include <stdlib.h>
//#include <ctype.h>
//#include <stdio.h>
#include <string.h>
//#include <time.h>
//#include <limits.h>
#include "crc16.h"                        
#include "LCD.h"                        /* Graphic LCD function prototypes    */
#include "rtc.h"                        


#include "types.h"
#include "keypad.h"
#include "main.h"
#include "clock.h"
#include "setup.h"

//#include "mathlib.h"


#include "main.h"

#endif /*include_h*/
